language: python
python:
  - "3.6"
install: 
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "pip install coverage"
  
script:
  - "nosetests --with-coverage --cover-erase"

notifications:
  email: false

after_success:
  - coveralls